#!/usr/bin/env python3
import subprocess
import sys
import tempfile


def main():
    cmd = ["python3", "/usr/local/bin/quackery.py"]
    if len(sys.argv) > 1:
        cmd.append(sys.argv[1])

    args = "\n".join(sys.argv[2:])
    with tempfile.TemporaryFile(mode="+wt") as f:
        f.write(args)
        f.flush()
        f.seek(0)
        result = subprocess.run(
            cmd, stdin=f, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding="utf-8"
        )

    output = result.stdout.rstrip("\n")
    print(output)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
